FROM tensorflow/tensorflow:1.4.0-rc1-devel-py3

# add python library
RUN pip --no-cache-dir install \
        keras \
        pandas \
        Pillow \
        h5py && \
	apt-get update && \
	apt-get install -y vim && \
	apt-get clean && \
	rm -rf /var/lib/apt/lists/*
	mv /usr/bin/python /usr/bin/python2 && \
	ln -s /usr/bin/python3.5 /usr/bin/python
	
WORKDIR POSE

COPY util util/

COPY openpose openpose/

COPY openpose/train.py train.py

